###################################################
# 前端 oms-front
##################################################
kind: Service
apiVersion: v1
metadata:
  name: fznews-front
spec:
  selector:
    app: fznews-front
  ports:
  #service虚拟端口
  - port: 8080
    protocol: TCP
    #各node节点开启的端口，端口范围 30000-32767
    nodePort: 30001
  type: NodePort      #type 为nodePort 外部网络才能访问
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fznews-front
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: fznews-front
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: fznews-front
    spec:
      containers:
      - name: fznews-front
        image: registry.cn-hangzhou.aliyuncs.com/mumushuiding/fznews
        imagePullPolicy: Always
        resources:
          limits:
            memory: "800Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080